WebSite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('teams/', include('teams.urls')),
    path('tournament/', include('tournament.urls')),
    path('', include('principal.urls')),
    path('not_found/', include('not_found.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WebSite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # added the word 'specifics'
    # path('specifics/<int:question_id>/', views.detail, name='detail'),
]

WebSite/principal/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin
from django.views.generic.base import TemplateView

app_name = 'principal'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: //
    path('', views.IndexView.as_view(), name='index'),
]

WebSite/teams/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin

app_name = 'teams'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: /teams/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /teams/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebSite/tournament/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin
from django.urls import include

app_name = 'tournament'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: /tournament/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /tournament/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebSite/principal/views.py
import datetime

from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from teams.models import Team
from tournament.models import Tournaments

class IndexView(generic.ListView):
    template_name = 'principal/index.html'
    context_object_name = 'index'

    def get_queryset(self):
        """Return the first five teams."""
        return Team.objects.order_by('team_name')[:5]

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'tournament_started': Tournaments.objects.filter(tournament_start_date__lte = datetime.date.today()).filter(tournament_end_date__gte = datetime.date.today())[:4],
            'tournament_open': Tournaments.objects.filter(tournament_start_date__gte = datetime.date.today() + datetime.timedelta(days=1)).order_by('tournament_start_date')[:4],
            'tournament_close': Tournaments.objects.filter(tournament_end_date__lt = datetime.date.today()).order_by('tournament_end_date')[:4],
            'more_context': Tournaments.objects.all(),
            'latest_team_list': Team.objects.order_by('team_name')[:4],
        })
        return context

WebSite/principal/templates/principal/index.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'teams/style.css' %}">
    <title>Inicio</title>
</head>

<body>

    {% include "header.html" %}

    <h1 class="header center">Proyecto PAP</h1>
    <div class="container section white">
        <div class="card grey">
            <div class="row container">
                <h2 class="header center">Equipos</h2>
                <p class="grey-text text-darken-3 lighten-3">Clubes de futbol que participan en los torneos y ligas organizados mediante CriptoFut.</p>
            </div>

            <div class="container row  grey lighten-2">
                
                    {% if latest_team_list %}
                        {% for team in latest_team_list %}
                        <div class="col l3 m3 s12 center-align">
                            <a href="{% url 'teams:detail' team.id %}">
                                {% load responsive_images %}
                                <img class="img responsive-img" src={{team.team_image}}>
                                <h5 class="black-text ">{{ team.team_name }}</h5>
                            </a>
                        </div>
                        {% endfor %}
                    {% else %}
                    <p>No teams are available.</p>
                    {% endif %}
            </div>

            <div class="center-align">
                <a class="red darken-4  waves-effect waves-purple btn-small" href="{% url 'teams:index' %}">Ver todos</a>
            </div>

            <div class="section white">
                <div class="card grey">
                    <div class="row container">
                        <h2 class="header center">Torneos</h2>
                        <p class="grey-text text-darken-3 lighten-3">Eventos deportivos de corta duración, celebrados con una menor cantidad de equipos.</p>
                    </div>

                    <div class="card grey lighten-1">
                        <h4 class="center-align">Torneos Abiertos</h4>
                        {% if tournament_open %}
                            {% for tournament in tournament_open %}
                                <div class="container">
                                    {% include "tournament.html" %}
                                </div>
                        {% endfor %}
                        {% else %}
                        <div class="container">
                            <div class="row center-align">
                                <h6 class="white-text caption">Nothing to show yet</h6>
                            </div>
                        </div>
                        {% endif %}
                        <div class="center-align">
                            <a class="red darken-4  waves-effect waves-purple btn-small" href="{% url 'tournament:index' %}">Ver todos</a>
                        </div>
                    </div>

                    <div class="card grey lighten-1">
                        <h4 class="center-align">Ligas Abiertas</h4>
                        <div class="row center-align">
                            <h6 class="white-text caption">Nothing to show yet</h6>
                        </div>
                        <div class="center-align">
                            <a class="red darken-4  waves-effect waves-purple btn-small" href="{% url 'tournament:index' %}">Ver todos</a>
                        </div>
                    </div>

                    <div class="card grey lighten-1">
                        <h4 class="center-align">Torneos en Curso</h4>
                        {% if tournament_started %}
                            {% for tournament in tournament_started %}
                                <div class="container">
                                    {% include "tournament.html" %}
                                </div>
                        {% endfor %}
                        {% else %}
                        <div class="container">
                            <div class="row center-align">
                                <h6 class="white-text caption">Nothing to show yet</h6>
                            </div>
                        </div>
                        {% endif %}
                        <div class="center-align">
                            <a class="red darken-4  waves-effect waves-purple btn-small" href="{% url 'tournament:index' %}">Ver todos</a>
                        </div>
                    </div>
                    <div class="card grey lighten-1">
                        <h4 class="center-align">Torneos en terminados</h4>
                        {% if tournament_close %}
                            {% for tournament in tournament_close %}
                                <div class="container">
                                    {% include "tournament.html" %}
                                </div>
                        {% endfor %}
                        {% else %}
                        <div class="container">
                            <div class="row center-align">
                                <h6 class="white-text caption">Nothing to show yet</h6>
                            </div>
                        </div>
                        {% endif %}
                        <div class="center-align">
                            <a class="red darken-4  waves-effect waves-purple btn-small" href="{% url 'tournament:index' %}">Ver todos</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

        {% load static %}
        <script src="{% static 'teams/index.js' %}"></script>

        {% load static %}
        <script src="{% static 'tournament/index.js' %}"></script>

        {% include "footer.html" %}

</body>