WebSite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('teams/', include('teams.urls')),
    path('tournament/', include('tournament.urls')),
    path('', include('principal.urls')),
    path('not_found/', include('not_found.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WebSite/not_found/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin
from django.views.generic.base import TemplateView

app_name = 'not_found'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: /not_found/
    path('', TemplateView.as_view(template_name='not_found.html'), name='index'),
]

WebSite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # added the word 'specifics'
    # path('specifics/<int:question_id>/', views.detail, name='detail'),
]

WebSite/principal/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin
from django.views.generic.base import TemplateView

app_name = 'principal'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: //
    path('', views.IndexView.as_view(), name='index'),
]

WebSite/teams/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin

app_name = 'teams'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: /teams/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /teams/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebSite/tournament/urls.py
from django.urls import path, re_path

from . import views
from django.contrib import admin
from django.urls import include

app_name = 'tournament'
urlpatterns = [
    re_path(r"^admin/", admin.site.urls, name="admin"),
    # ex: /tournament/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /tournament/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebSite/not_found/models.py
from django.db import models

# Create your models here.

WebSite/tournament/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Tournaments(models.Model):
    tournament_name = models.CharField(max_length=200)
    tournament_city = models.CharField(max_length=100)
    tournament_start_date = models.DateTimeField('start date')
    tournament_end_date = models.DateTimeField('end date')

    def __str__(self):
        return "Nombre: " + self.tournament_name + ", Ciudad: " + self.tournament_city + ", Fecha de inicio: " + self.tournament_start_date.strftime("%d %B %Y") + ", Duaración: " + self.duration + " días"

    def next_tournaments(self):
        return self.tournament_start_date >= timezone.now()

    @property
    def is_in_progress(self):
        return (self.tournament_end_date >= timezone.now() and self.tournament_start_date <= timezone.now())

    @property
    def duration(self):
        return str((self.tournament_end_date - self.tournament_start_date).days)

WebSite/not_found/views.py
from django.shortcuts import render

# Create your views here.

WebSite/tournament/views.py
import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Tournaments
from teams.models import Teams_Tournaments


class IndexView(generic.ListView):
    template_name = 'tournament/index.html'
    model = Tournaments
    context_object_name = 'tournaments'

    def get_queryset(self):
        """Return the last five published polls."""
        return Tournaments.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'tournament_started': Tournaments.objects.filter(tournament_start_date__lte = datetime.date.today()).filter(tournament_end_date__gte = datetime.date.today())[:9],
            'tournament_open': Tournaments.objects.filter(tournament_start_date__gte = datetime.date.today() + datetime.timedelta(days=1)).order_by('tournament_start_date')[:9],
            'tournament_close': Tournaments.objects.filter(tournament_end_date__lt = datetime.date.today()).order_by('tournament_end_date')[:9],
            'more_context': Tournaments.objects.all(),
        })
        return context

class DetailView(generic.DetailView):
    model = Tournaments
    template_name = 'tournament/detail.html'

WebSite/templates/footer.html
<footer class="page-footer red lighten-4 ">
    <div class="container black-text">
        <div class="row" id="foot">
            <div class="col l6  s12">
                <h6><b>SOBRE NOSOTROS</b></h6>
                <p>Nosotros proveemos una solución a tus necesidades logisticas, organizando tu torneo desde cero y ayudandote a gestionar y visualizar los resultados.</p>
                <h6><b>RECIBE LAS NOVEDADES</b></h6>
                <p>Si quieres recibir noticias sobre torneos y ligas abiertas en cuanto se abran, puedes suscribirte a nuestro newsletter.</p>
                <div class="row">
                    <form class="col s12">
                        <div class="row">
                            <div class="input-field col l7 s7 ">
                                <i class="material-icons prefix">account_circle</i>
                                <input id="icon_prefix" type="text" class="validate">
                                <label for="icon_prefix">Nombre</label>
                            </div>
                            <div class="input-field col l7 s7">
                                <i class="material-icons prefix">email</i>
                                <input id="icon_telephone" type="tel" class="validate">
                                <label for="icon_telephone">Mail</label>
                            </div>
                            <div class="input-field col l7 s7">
                                <button class="btn waves-effect waves-light  grey darken-2" type="submit"
                                    name="action">Enviar
                                    <i class="material-icons right">send</i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr class="col s12 hide-on-large-only">
            <div class="col l4 offset-l2 s12 black-text">
                <h6><b>CONTÁCTANOS</b></h6>
                <p>Si te interesa entrar en el programa de lealtad, con el cual obtendras beneficios, escribenos para hacerte llegar la convocatoria.</p>
                <div class="row">
                    <form class="col s12">
                        <div class="row">
                            <div class="input-field col s6">
                                <input id="input_text" type="text" data-length="10">
                                <label for="input_text">Nombre</label>
                            </div>
                            <div class="input-field col s6">
                                <input id="input_text" type="text" data-length="10">
                                <label for="input_text">Apellido</label>
                            </div>
                            <div class="input-field col s6">
                                <input id="input_text" type="text" data-length="10">
                                <label for="input_text">Mail</label>
                            </div>
                            <div class="input-field col s12">
                                <textarea id="textarea2" class="materialize-textarea" data-length="120"></textarea>
                                <label for="textarea2">Escríbenos tus mensajes</label>
                            </div>
                            <div class="input-field col l7 s7">
                                <button class="btn waves-effect waves-light  grey darken-2" type="submit"
                                    name="action">Enviar
                                    <i class="material-icons right">send</i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright black text-white">
        <div class="container text-white">
            <p class="center">
                © 2021 - Nombre de la Empresa
            </p>
            <br class="hide-on-small-only">
            <div class="row center">
                <a class="white-text col m4 s12" href="#!"><i class="material-icons prefix">email</i>pap_equipo_defi@correo.com</a>
                <a class="white-text col m4 s12" href="#!"><i class="material-icons prefix">call</i>+52 33 3345 6541</a>
                <a class="white-text col m4 s12" href="#!"><span class="iconify" data-icon="brandico:facebook" data-inline="false"></span> <span class="iconify" data-icon="mdi-twitter" data-inline="false"></span> <span class="iconify" data-icon="akar-icons:instagram-fill" data-inline="false"></span> <span class="iconify" data-icon="ant-design:reddit-outlined" data-inline="false"></span></a>
            </div>
            <br class="hide-on-small-only">
            <div class="row center">
                <a class="white-text col m4 s12" href="#!">Mapa de Sitio</a>
                <a class="white-text col m4 s12" href="#!">Términos y Condiciones</a>
                <a class="white-text col m4 s12" href="#!">Privacidad</a>
            </div>
        </div>
    </div>
</footer>

WebSite/templates/header.html
<div class="header">
    <nav class="red darken-4">
        <div class="container nav-wrapper">
            <a href="{% url 'principal:index' %}" class="brand-logo"><i class="material-icons">sports_soccer</i>CriptoFut</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'principal:index' %}">INICIO</a></li>
                <li><a href="{% url 'tournament:index' %}">TORNEOS</a></li>
                <li><a href="{% url 'teams:index' %}">EQUIPOS</a></li>
                <li><a href="{% url 'not_found:index' %}">CANCHAS</a></li>
                <li><a href="{% url 'not_found:index' %}">ARBITROS</a></li>
                <li><a href="{% url 'admin:index' %}">LOG IN/SIGN UP</a></li>
            </ul>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        <li><a href="{% url 'principal:index' %}">INICIO</a></li>
        <li><a href="{% url 'tournament:index' %}">TORNEOS</a></li>
        <li><a href="{% url 'teams:index' %}">EQUIPOS</a></li>
        <li><a href="{% url 'not_found:index' %}">CANCHAS</a></li>
        <li><a href="{% url 'not_found:index' %}">ARBITROS</a></li>
        <li><a href="{% url 'admin:index' %}">LOG IN/SIGN UP</a></li>
</div>

WebSite/templates/not_found.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'teams/style.css' %}">
    <title>404</title>
</head>

<body>

    {% include "header.html" %}
    <div class="container">
        <div class="section white">
            <div class="row container">
                <h1 class="header center-align">404</h1>
                <h2 class="header center-align">NOT FOUND</h2>
                <h5 class="grey-text text-darken-3 lighten-3 center-align">Lo sentimos esta parte del proyecto todavía no existe. Esto todavía es un trabajo en proceso.</h5>
            </div>
        </div>
        <div class="parallax-container">
            <div class="parallax"><img src="https://i.imgur.com/HVWORsR.jpg"></div>
        </div>
    </div>

    {% load static %}
    <script src="{% static 'teams/index.js' %}"></script>

    {% include "footer.html" %}

</body>

WebSite/templates/tournament.html
<tournament>
    <div class="col s6 m4 l4">
        <a href="{% url 'tournament:detail' tournament.id %}">
            <div class="card-panel grey lighten-2 z-depth-4 flow-text">
                <span>
                    <div class="row valign-wrapper black-text">
                        <div class="col s6 center-align">
                            <i class="material-icons large">emoji_events</i>
                        </div>
                        <div class="col s6">
                            <b>{{ tournament.tournament_name }}</b> <span class="iconify"
                                data-icon="clarity:group-solid-badged" data-inline="false"></span>
                            <br>
                            {{ tournament.duration }} dias - {{ tournament.tournament_city }}
                        </div>
                    </div>
                </span>
            </div>
        </a>
    </div>
</tournament>